version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: chat_db
    env_file:
      ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat_network

volumes:
  postgres_data:

networks:
  chat_network:
    driver: bridge